import localFont from "next/font/local";
import Home from "./page";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="m-0 p-0">
      <body className="m-0 p-0 bg-gradient-to-bl from-stone-50 to-red-100">
        {children}
      </body>
    </html>
  );
}
